name: Ren'Py Lint

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  RENPY_VERSION: ${{ vars.RENPY_VERSION || 'latest' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: project
        lfs: true

    - name: "Load Ren'Py from cache"
      id: cache-renpy
      uses: actions/cache@v4
      with:
        path: renpy
        key: ${{ runner.os }}-renpy-${{ env.RENPY_VERSION }}-core

    - name: "Install Ren'Py"
      uses: Ayowel/renpy-setup-action@v2
      if: steps.cache-renpy.outputs.cache-hit != 'true'
      with:
        action: install
        version: ${{ env.RENPY_VERSION }}
        install_dir: renpy

    - name: "Lint project"
      uses: Ayowel/renpy-setup-action@v2
      with:
        action: lint
        install_dir: renpy
        game: project
